[package]
name = "disperse-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.disperse]
path = ".."

[dependencies.elrond-wasm]
version = "0.27.0"

[dependencies.elrond-wasm-debug]
version = "0.27.0"
