[package]
name = "presale-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.presale]
path = ".."

[dependencies.elrond-wasm]
version = "0.20"

[dependencies.elrond-wasm-debug]
version = "0.20"
